### ISSUE TITLE
Unstable with DFP tags

### ISSUE THREAD

**Issue by kugaevsky** [WeCodePixels/theia-sticky-sidebar#7]
Thanks for great plugin!

It's really hard to get this error, but sometimes DFP iframe ads are removed from page after theia initialization. I have inner containers with `theiaStickySidebar` class, but it doesn't help.
Could you fix it or just give me an advice when I should initialize theia before or after fetching the ads?

**Comment by liviucmg** [comment]
Hmm, that sounds odd. Are you sure the inner container has the `theiaStickySidebar` class? If it does, then no DOM elements should be moved around, so the iframes should remain intact.

**Comment by moiseslagos** [comment]
I have the same problem, as I fix??? please help me!

**Comment by liviucmg** [comment]
Be sure you have the inner containers with `class="theiaStickySidebar"` right inside your sidebar.

**Comment by moiseslagos** [comment]
Thx so much!

Móises Lagos PachasDiseñador Gráfico - Web, FrontendTelf.: 963849113Facebook: /moises.lagospachas


Date: Wed, 2 Sep 2015 13:09:43 -0700

**Comment by liviucmg** [comment]
Let me know if it fixed your issue so I can close this. :) Cheers!

**Comment by moiseslagos** [comment]
<script src="<?php echo base_url();?>assets/js/sticky/theia-sticky-sidebar.js"></script><script>  $(document).ready(function() {    $('.contenido_principal_inner, .sidebar_home')      .theiaStickySidebar({        additionalMarginTop: 0      });    });</script>
<div class="contenido_principal_inner"></div><div class="sidebar_home"></div>
I agregge div class ="theiaStickySidebar"  --->
<div class="contenido_principal_inner"></div><div class="sidebar_home">    <div class="theiaStickySidebar"></div></div>
With that solved the problem. Without this class "theiaStickySidebar", the blocks did not include me DFP tags. 
I had not considerardo add that class, because I worked the same, but when adding the DFP did not work
Problema resuelto, Saludos desde Perú



Móises Lagos PachasDiseñador Gráfico - Web, FrontendTelf.: 963849113Facebook: /moises.lagospachas


Date: Wed, 2 Sep 2015 13:23:12 -0700

**Comment by liviucmg** [comment]
Awesome, glad it helped! The reason is works is because without the "theiaStickySidebar" class, the DOM elements are moved around and consequently the DFP ads are removed, since they are created using inline  JavaScript (document.write). Cheers!

**Comment by steelmaiden** [comment]
Guy i have the same problem on my theme https://geek.hr/znanost/

Sidebar ad appears and then quickly disappears.

Please help me find the fix for this!
